# Clash Config Make by Coldvvater
# TG Channel: https://t.me/Ison_Channel
# GitHub主页: https://github.com/Coldvvater
# Update Date: 2023.05.03

subscribe-url: 填上你的订阅链接
# 替换上面文字用于Stash获取机场流量信息并在主页显示

mixed-port: 7890
# 本地混合代理(http和socks5合并）端口
allow-lan: true
# 允许局域网连接(false/true)
bind-address:
# 监听IP白名单（当allow-lan：true），只允许列表设备
  '*'
# 全部设备
# 192.168.122.11
# 单个ip4地址
# "[aaaa::a8aa:ff:fe09:57d8]"
# 单个ip6地址
mode: rule
# clash工作模式（rule/global/direct）
log-level: info
# 日志等级（info/warning/error/debug/silent）
ipv6: true
# IP6解析开关；如果为false，将返回ip6结果为空
external-controller: 127.0.0.1:9090
# 控制器监听地址
dns:
# DNS模块设置
  enable: true
# DNS开关(false/true)
  listen: 0.0.0.0:1053
# DNS监听地址
  ipv6: true
# IP6解析开关；如果为false，将返回ip6结果为空
  default-nameserver:
# 解析非IP的dns用的dns服务器,只支持纯IP
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip
# DNS模式(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
# Fake-IP解析地址池
  fake-ip-filter:
# Fake-ip过滤，列表中的域名返回真实ip
    - '*.lan'
# Local Area Network
    - '+.stun.*.*'
# Stun Services
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'lens.l.google.com'
# Google Voices
    - '*.n.n.srv.nintendo.net'
# Nintendo Switch
    - '+.stun.playstation.net'
# PlayStation
    - 'xbox.*.*.microsoft.com'
# XBox
    - '*.*.xboxlive.com'
# Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
# Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
# 默认DNS服务器，支持udp/tcp/dot/doh/doq
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query

c: &c {type: http, behavior: classical, interval: 86400}
# 规则行为锚点

d: &d {type: http, behavior: domain, interval: 86400}

p: &p {type: http, interval: 42300, health-check: {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 300}}
# 代理提供商锚点

proxies: # 本地服务器

u: &u {type: select, use: [MySubs]}
# > 订阅引用锚点

proxy-providers: # 代理提供商(远程订阅)
  MySubs: &MySubs
    <<: *p
    url: ""
    path: ./proxy_providers/mysubs.yaml
# 1. 请使用Clash类型订阅链接填入引号""内使用,
# 2. 或可使用通用订阅链接通过Sub-Store进行订阅转换(用于Stash)。

proxy-groups: # 策略组

# 节点选择
- {name: PROXY, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Rocket.png, type: select, proxies: [HONGKONG,TAIWAN,SINGAPORE,JAPAN,AMERICA,OTHERS,WARP+]}

# 香港节点
- {name: HONGKONG, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Hong_Kong.png, type: url-test, <<: *u, filter: "港|🇭🇰|HK|(?i)Hong"}

# 台湾节点
- {name: TAIWAN, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/China.png, <<: *u, proxies: [DIRECT], filter: "台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan"}

# 狮城节点
- {name: SINGAPORE, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Singapore.png, type: url-test, <<: *u, filter: "新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore"}

# 日本节点
- {name: JAPAN, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Japan.png, type: url-test, <<: *u, filter: "日|🇯🇵|东京|JP|(?i)Japan"}

# 美国节点
- {name: AMERICA, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/United_States.png, type: url-test, <<: *u, filter: "美|🇺🇲|US|(?i)States|American"}

# 其他节点
- {name: OTHERS, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Airport.png, <<: *u, proxies: [DIRECT]}

# 漏网之鱼
- {name: FINAL, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/mini/Final.png, type: select, proxies: [PROXY,DIRECT]}

rule-providers: # 远程规则集

  Unbreak: # > 规则修正
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml"
    path: ./ruleset/Unbreak.yaml

  Advertising: # > 广告拦截
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/Advertising.yaml"
    path: ./ruleset/Advertising.yaml

  OpenAI: # > OpenAI
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Mononoke/master/Stash/RuleSet/OpenAI.yaml"
    path: ./ruleset/OpenAI.yaml

  BiliIntl: # 哔哩哔哩东南亚
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.yaml"
    path: ./ruleset/BiliIntl.yaml

  BiliBili: # 哔哩哔哩
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml

  GlobalMedia: # 国际媒体
    <<: *d
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml"
    path: ./ruleset/GlobalMedia.yaml

  Telegram: # 电报信息
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/Telegram.yaml

  Bing: # 必应搜索
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml"
    path: ./ruleset/Bing.yaml

  TestFlight: # TestFlight
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TestFlight/TestFlight.yaml"
    path: ./ruleset/TestFlight.yaml

  Apple: # 苹果服务
    <<: *d
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml"
    path: ./ruleset/Apple.yaml

  Microsoft: # 微软服务
    <<: *c
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml

  ChinaMax_Domain: # 国内网站
    <<: *d
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml"
    path: ./ruleset/ChinaMax_Domain.yaml

  Global_Domain: # 国外网站
    <<: *d
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml"
    path: ./ruleset/Global_Domain.yaml

rules: # 分流规则引用
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Advertising,REJECT
  - RULE-SET,OpenAI,AMERICA
  - RULE-SET,BiliIntl,PROXY
  - RULE-SET,BiliBili,TAIWAN
  - RULE-SET,GlobalMedia,PROXY
  - RULE-SET,Telegram,SINGAPORE
  - RULE-SET,Bing,PROXY
  - RULE-SET,TestFlight,PROXY
  - RULE-SET,Apple,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Global_Domain,PROXY
  - RULE-SET,ChinaMax_Domain,DIRECT
  - GEOIP,Lan,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,FINAL


