# Clash Config Make by Coldvvater
# TG Channel: https://t.me/Ison_Channel
# GitHub主页: https://github.com/Coldvvater
# Update Date: 2023.05.15

mixed-port: 7890
# 本地混合代理(http和socks5合并）端口
allow-lan: true
# 允许局域网连接(false/true)
bind-address:
# 监听IP白名单（当allow-lan：true），只允许列表设备
  '*'
# 全部设备
# 192.168.122.11
# 单个ip4地址
# "[aaaa::a8aa:ff:fe09:57d8]"
# 单个ip6地址
mode: rule
# clash工作模式（rule/global/direct）
log-level: info
# 日志等级（info/warning/error/debug/silent）
ipv6: true
# IP6解析开关；如果为false，将返回ip6结果为空
external-controller: 127.0.0.1:9090
# 控制器监听地址
dns:
# DNS模块设置
  enable: true
# DNS开关(false/true)
  listen: 0.0.0.0:1053
# DNS监听地址
  ipv6: true
# IP6解析开关；如果为false，将返回ip6结果为空
  default-nameserver:
# 解析非IP的dns用的dns服务器,只支持纯IP
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  enhanced-mode: fake-ip
# DNS模式(redir-host/fake-ip)
  fake-ip-range: 198.18.0.1/16
# Fake-IP解析地址池
  fake-ip-filter:
# Fake-ip过滤，列表中的域名返回真实ip
    - '+.lan'
# Local Area Network
    - '+.stun.*.*'
# Stun Services
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'lens.l.google.com'
# Google Voices
    - '*.n.n.srv.nintendo.net'
# Nintendo Switch
    - '+.stun.playstation.net'
# PlayStation
    - 'xbox.*.*.microsoft.com'
# XBox
    - '*.*.xboxlive.com'
# Microsoft
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
# Bilibili CDN
    - '*.mcdn.bilivideo.cn'
  nameserver:
# 默认DNS服务器，支持udp/tcp/dot/doh/doq
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query

  # TUN模式
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

